const express = require('express');
const mustacheExpress = require('mustache-express');
const Mustache = require('mustache');
const cookieParser = require('cookie-parser');
const path = require('path');
const fs = require('fs');
const { execFileSync } = require('child_process');
const { marked } = require('marked');
const app = express();
const port = process.env.PORT || 3000;
const PUREADMIN_API = process.env.PUREADMIN_API || 'https://pureadmin.io';

// Path to the core package in workspace
const corePackagePath = path.join(__dirname, '..', 'packages', 'core');

// Core package version — shown next to the brand in the navbar.
const coreVersion = JSON.parse(fs.readFileSync(path.join(corePackagePath, 'package.json'), 'utf-8')).version;

// Load theme config from pureadmin.json + .pureadmin.json
const repoRoot = path.join(__dirname, '..');

function loadThemes() {
    let themes = {};

    // Load standard themes (checked in / generated by Docker build)
    const standardPath = path.join(repoRoot, 'pureadmin.json');
    if (fs.existsSync(standardPath)) {
        const standard = JSON.parse(fs.readFileSync(standardPath, 'utf-8'));
        themes = { ...themes, ...standard.themes };
    }

    // Merge user's private themes (gitignored)
    const localPath = path.join(repoRoot, '.pureadmin.json');
    if (fs.existsSync(localPath)) {
        const local = JSON.parse(fs.readFileSync(localPath, 'utf-8'));
        themes = { ...themes, ...local.themes };
    }

    // Resolve paths and validate
    const resolved = {};
    for (const [name, config] of Object.entries(themes)) {
        // Support both formats:
        //   Old: "audi": "../path/to/audi"
        //   New: "audi": { "path": "../path/to/audi" } or "audi": {}
        let themePath;
        if (typeof config === 'string') {
            themePath = config;
        } else if (config && config.path) {
            themePath = config.path;
        } else {
            // No path — check ./themes/{name} (downloaded themes)
            themePath = path.join('themes', name);
        }

        const absPath = path.resolve(repoRoot, themePath);
        const distPath = path.join(absPath, 'dist');
        if (fs.existsSync(distPath)) {
            resolved[name] = distPath;
        } else {
            console.warn(`Theme "${name}" not found at ${absPath}, skipping`);
        }
    }

    return resolved;
}

const themePackages = loadThemes();

// Negative cache: slug -> timestamp of last failed attempt
const failedThemes = new Map();
const FAILED_THEME_TTL_MS = 10 * 60 * 1000; // 10 minutes

// Downloads a theme on demand from pureadmin.io and registers it
async function ensureTheme(themeName) {
    if (themePackages[themeName]) return true;

    // Only allow safe slug characters
    if (!/^[a-z0-9-]+$/.test(themeName)) return false;

    // Check negative cache
    const failedAt = failedThemes.get(themeName);
    if (failedAt && Date.now() - failedAt < FAILED_THEME_TTL_MS) return false;

    console.log(`Theme "${themeName}" not found locally, downloading from ${PUREADMIN_API}...`);

    try {
        const res = await fetch(`${PUREADMIN_API}/api/themes/${themeName}/download`);
        if (!res.ok) {
            console.warn(`Download failed for "${themeName}": ${res.status}`);
            failedThemes.set(themeName, Date.now());
            return false;
        }

        const zipPath = path.join('/tmp', `${themeName}.zip`);
        const themePath = path.join(repoRoot, 'themes', themeName);

        const buffer = Buffer.from(await res.arrayBuffer());
        fs.writeFileSync(zipPath, buffer);

        fs.mkdirSync(themePath, { recursive: true });
        execFileSync('unzip', ['-o', zipPath, '-d', themePath], { stdio: 'ignore' });
        fs.unlinkSync(zipPath);

        // Raw theme ZIPs have css/, but demo server expects dist/
        const cssPath = path.join(themePath, 'css');
        const distPath = path.join(themePath, 'dist');
        if (fs.existsSync(cssPath) && !fs.existsSync(distPath)) {
            fs.renameSync(cssPath, distPath);
        }

        if (fs.existsSync(distPath)) {
            // Published ZIPs ship a full theme.json (modes, colorVariants,
            // features etc.). Only fall back to API metadata if the ZIP
            // didn't include one — overwriting a complete manifest with
            // the API's trimmed record was stripping modes/variants and
            // breaking the settings panel.
            const manifestPath = path.join(themePath, 'theme.json');
            if (!fs.existsSync(manifestPath)) {
                try {
                    const metaRes = await fetch(`${PUREADMIN_API}/api/themes/${themeName}`);
                    if (metaRes.ok) {
                        const { theme } = await metaRes.json();
                        if (theme) {
                            fs.writeFileSync(manifestPath, JSON.stringify(theme, null, 2));
                        }
                    }
                } catch (e) {
                    console.warn(`Could not fetch metadata for "${themeName}":`, e.message);
                }
            }

            themePackages[themeName] = distPath;
            console.log(`Theme "${themeName}" downloaded and registered.`);
            return true;
        }

        console.warn(`Theme "${themeName}" extracted but no dist/ found.`);
        failedThemes.set(themeName, Date.now());
        return false;
    } catch (e) {
        console.error(`Failed to download theme "${themeName}":`, e.message);
        failedThemes.set(themeName, Date.now());
        return false;
    }
}

// Set Mustache as template engine
app.engine('mustache', mustacheExpress());
app.set('view engine', 'mustache');
app.set('views', path.join(__dirname, 'views'));

// Helper to load partials
const loadPartial = (name) => {
    return fs.readFileSync(path.join(__dirname, 'views', 'partials', `${name}.mustache`), 'utf-8');
};

// Build the partials map so PAGE templates can use {{> partials/<name>}} (e.g.
// a shared printer icon reused across print buttons). Keyed as "partials/<name>"
// to match the {{> partials/x}} reference form. Re-read each request for dev.
const buildPagePartials = () => {
    const dir = path.join(__dirname, 'views', 'partials');
    const map = {};
    for (const file of fs.readdirSync(dir)) {
        if (file.endsWith('.mustache')) {
            map[`partials/${file.replace(/\.mustache$/, '')}`] = fs.readFileSync(path.join(dir, file), 'utf-8');
        }
    }
    return map;
};

// Block path traversal and dangerous characters
const BLOCKED_PATTERNS = ['..', '\\', '%2e', '%2E', '%5c', '%5C', '%00'];
app.use((req, res, next) => {
    const url = req.originalUrl;
    if (BLOCKED_PATTERNS.some(p => url.includes(p))) {
        return res.status(400).send('Bad request');
    }
    next();
});

// Add cookie parser middleware
app.use(cookieParser());

// Middleware to determine current theme, container width, and sidebar mode
app.use(async (req, res, next) => {
    const DEFAULT_THEME = 'audi';

    let theme = req.query.theme || req.cookies.selectedTheme || DEFAULT_THEME;

    // Try to download the theme on-demand if not available locally
    if (!themePackages[theme]) {
        await ensureTheme(theme);
    }

    // Validate theme exists - if not, clear cookie and use default
    if (!themePackages[theme]) {
        console.warn(`Invalid theme "${theme}" requested, falling back to "${DEFAULT_THEME}"`);
        theme = DEFAULT_THEME;
        // Clear the invalid cookie
        res.clearCookie('selectedTheme');
    }

    res.locals.currentTheme = theme;

    // Set cookie if theme was changed via query param (and is valid)
    if (req.query.theme && themePackages[req.query.theme]) {
        res.cookie('selectedTheme', req.query.theme, { maxAge: 365 * 24 * 60 * 60 * 1000 }); // 1 year
    }

    // Container width
    const containerWidth = req.query.containerWidth || req.cookies.containerWidth || 'fluid';
    res.locals.containerWidth = containerWidth;

    // Set cookie if container width was changed via query param
    if (req.query.containerWidth !== undefined) {
        res.cookie('containerWidth', containerWidth, { maxAge: 365 * 24 * 60 * 60 * 1000 }); // 1 year
    }

    // Sidebar mode
    const sidebarMode = req.query.sidebarMode !== undefined ? req.query.sidebarMode : (req.cookies.sidebarMode || '');
    res.locals.sidebarMode = sidebarMode;

    // Set cookie if sidebar mode was changed via query param
    if (req.query.sidebarMode !== undefined) {
        res.cookie('sidebarMode', sidebarMode, { maxAge: 365 * 24 * 60 * 60 * 1000 }); // 1 year
    }

    // Mode override (light/dark)
    if (req.query.mode) {
        res.locals.modeOverride = req.query.mode;
    }

    // Color variant override
    if (req.query.colorVariant) {
        res.locals.colorVariantOverride = req.query.colorVariant;
    }

    // Add helper variables for Mustache
    res.locals.isAudiTheme = theme === 'audi';
    res.locals.coreVersion = coreVersion;

    next();
});

// Custom render helper for layout support
const renderWithLayout = (res, viewName, data) => {
    // Merge data with res.locals
    const viewData = { ...res.locals, ...data };

    // Read and render the page template
    const pageTemplate = fs.readFileSync(path.join(__dirname, 'views', `${viewName}.mustache`), 'utf-8');
    const pageHtml = Mustache.render(pageTemplate, viewData, buildPagePartials());

    // Read and render partials WITH data
    const navbarTemplate = loadPartial('navbar');
    const sidebarTemplate = loadPartial('sidebar');
    const settingsPanelTemplate = loadPartial('settings-panel');
    const navbarHtml = Mustache.render(navbarTemplate, viewData);
    const sidebarHtml = Mustache.render(sidebarTemplate, viewData);
    const settingsPanelHtml = Mustache.render(settingsPanelTemplate, viewData);

    // Read layout template fresh on each request (for development)
    const layoutTemplate = fs.readFileSync(path.join(__dirname, 'views', 'layout.mustache'), 'utf-8');

    // Render the layout with the page content and rendered partials
    const finalData = {
        ...viewData,
        body: pageHtml,
        partials: {
            navbar: navbarHtml,
            sidebar: sidebarHtml,
            settingsPanel: settingsPanelHtml
        }
    };
    const finalHtml = Mustache.render(layoutTemplate, finalData);

    res.send(finalHtml);
};

// Routes
// Top-level pages
app.get('/', (req, res) => {
    renderWithLayout(res, 'dashboard', { pageTitle: 'Dashboard', currentPage: 'dashboard', isDashboard: true });
});

// Search results — the landing page for the type-and-go search variants
// (pc-navbar-search--input / pc-sidebar__search--input), which submit here via a
// native GET. Demo only: it just echoes ?q= so the redirect lands somewhere real;
// a real app runs the query. {{q}} is Mustache-escaped in the view, so it's safe.
app.get('/search', (req, res) => {
    const q = (req.query.q || '').toString();
    renderWithLayout(res, 'search', { pageTitle: 'Search', currentPage: 'search', q: q, hasQuery: q.trim().length > 0 });
});

// Minimal-shell example: no sidebar, no burger, full-width content. Rendered
// through the SAME layout as every other page but with simpleLayout:true, which
// drops the sidebar + burger + header menu and the sidebar-only settings — so
// the real settings panel (theme, layout width, search box, RTL, profile, fonts)
// still works here unchanged.
app.get('/examples/simple-app', (req, res) => {
    renderWithLayout(res, 'examples/simple-app', { pageTitle: 'Simple App', currentPage: 'simple-app', simpleLayout: true });
});

app.get('/getting-started', (req, res) => {
    renderWithLayout(res, 'getting-started', { pageTitle: 'Getting Started', currentPage: 'getting-started', isGettingStarted: true });
});

app.get('/changelog', (req, res) => {
    const changelogPath = path.join(corePackagePath, 'CHANGELOG.md');
    const changelogMd = fs.readFileSync(changelogPath, 'utf-8');
    const changelogHtml = marked(changelogMd);
    renderWithLayout(res, 'changelog', { pageTitle: 'Changelog', currentPage: 'changelog', isChangelog: true, changelogContent: changelogHtml });
});

app.get('/forms', (req, res) => {
    renderWithLayout(res, 'forms', { pageTitle: 'Forms', currentPage: 'forms', isForms: true });
});

// Design
app.get('/design/theme-variables', (req, res) => {
    renderWithLayout(res, 'theme-variables', { pageTitle: 'Theme Variables', currentPage: 'theme-variables', isThemeVariables: true });
});

app.get('/design/colors', (req, res) => {
    renderWithLayout(res, 'colors', { pageTitle: 'Colors', currentPage: 'colors', isColors: true });
});

app.get('/design/icons', (req, res) => {
    renderWithLayout(res, 'icons', { pageTitle: 'Icons', currentPage: 'icons', isIcons: true });
});

app.get('/design/helpers', (req, res) => {
    renderWithLayout(res, 'helpers', { pageTitle: 'Helpers', currentPage: 'helpers', isHelpers: true });
});

app.get('/design/layouts', (req, res) => {
    renderWithLayout(res, 'layouts', { pageTitle: 'Layouts', currentPage: 'layouts', isLayouts: true });
});

// Components
app.get('/components/overview', (req, res) => {
    renderWithLayout(res, 'components', { pageTitle: 'Components', currentPage: 'components', isComponents: true });
});

app.get('/components/buttons', (req, res) => {
    renderWithLayout(res, 'buttons', { pageTitle: 'Buttons', currentPage: 'buttons', isButtons: true });
});

app.get('/components/inputs', (req, res) => {
    renderWithLayout(res, 'inputs', { pageTitle: 'Inputs', currentPage: 'inputs', isInputs: true });
});

app.get('/components/validations', (req, res) => {
    renderWithLayout(res, 'validations', { pageTitle: 'Form Validations', currentPage: 'validations', isValidations: true });
});

app.get('/components/date-picker', (req, res) => {
    renderWithLayout(res, 'date-picker', { pageTitle: 'Date Picker', currentPage: 'date-picker', isDatePicker: true });
});

app.get('/components/multiselect', (req, res) => {
    renderWithLayout(res, 'multiselect', { pageTitle: 'Multiselect', currentPage: 'multiselect', isMultiselect: true });
});

app.get('/components/data-grid', (req, res) => {
    renderWithLayout(res, 'data-grid', { pageTitle: 'Data Grid', currentPage: 'data-grid', isDataGrid: true });
});

app.get('/components/svelte-treeview', (req, res) => {
    renderWithLayout(res, 'svelte-treeview', { pageTitle: 'Svelte Treeview', currentPage: 'svelte-treeview', isSvelteTreeview: true });
});

app.get('/components/file-selector', (req, res) => {
    renderWithLayout(res, 'file-selector', { pageTitle: 'File Upload', currentPage: 'file-selector', isFileSelector: true });
});

app.get('/components/checkbox-lists', (req, res) => {
    renderWithLayout(res, 'checkbox-lists', { pageTitle: 'Checkbox Lists', currentPage: 'checkbox-lists', isCheckboxLists: true });
});

app.get('/components/cards', (req, res) => {
    renderWithLayout(res, 'cards', { pageTitle: 'Cards', currentPage: 'cards', isCards: true });
});

app.get('/components/sizing', (req, res) => {
    renderWithLayout(res, 'sizing', { pageTitle: 'Sizing & Layout', currentPage: 'sizing', isSizing: true });
});

app.get('/components/fit-to-size', (req, res) => {
    renderWithLayout(res, 'fit-to-size', { pageTitle: 'Fit to Size', currentPage: 'fit-to-size', isFitToSize: true });
});

app.get('/responsivity', (req, res) => {
    renderWithLayout(res, 'responsivity', { pageTitle: 'Responsivity — How It Works', currentPage: 'responsivity', isResponsivity: true });
});

app.get('/components/grid', (req, res) => {
    renderWithLayout(res, 'grid', { pageTitle: 'Grid System', currentPage: 'grid', isGrid: true });
});

app.get('/components/tabs', (req, res) => {
    renderWithLayout(res, 'tabs', { pageTitle: 'Tabs', currentPage: 'tabs', isTabs: true });
});

app.get('/components/badges', (req, res) => {
    renderWithLayout(res, 'badges', { pageTitle: 'Badges & Labels', currentPage: 'badges', isBadges: true });
});

app.get('/components/lists', (req, res) => {
    renderWithLayout(res, 'lists', { pageTitle: 'Lists', currentPage: 'lists', isLists: true });
});

app.get('/components/document', (req, res) => {
    renderWithLayout(res, 'document', { pageTitle: 'Document', currentPage: 'document', isDocument: true });
});

app.get('/components/sheet', (req, res) => {
    renderWithLayout(res, 'sheet', { pageTitle: 'Sheet (Invoice)', currentPage: 'sheet', isSheet: true });
});

app.get('/components/code', (req, res) => {
    renderWithLayout(res, 'code', { pageTitle: 'Code Display', currentPage: 'code', isCode: true });
});

app.get('/components/alerts', (req, res) => {
    renderWithLayout(res, 'alerts', { pageTitle: 'Alerts', currentPage: 'alerts', isAlerts: true });
});

app.get('/components/callouts', (req, res) => {
    renderWithLayout(res, 'callouts', { pageTitle: 'Callouts', currentPage: 'callouts', isCallouts: true });
});

app.get('/components/toasts', (req, res) => {
    renderWithLayout(res, 'toasts', { pageTitle: 'Toast Notifications', currentPage: 'toasts', isToasts: true });
});

app.get('/components/loaders', (req, res) => {
    renderWithLayout(res, 'loaders', { pageTitle: 'Loaders & Spinners', currentPage: 'loaders', isLoaders: true });
});

app.get('/components/pagers', (req, res) => {
    renderWithLayout(res, 'pagers', { pageTitle: 'Pagers', currentPage: 'pagers', isPagers: true });
});

app.get('/components/tooltips', (req, res) => {
    renderWithLayout(res, 'tooltips', { pageTitle: 'Tooltips', currentPage: 'tooltips', isTooltips: true });
});

app.get('/components/modals', (req, res) => {
    renderWithLayout(res, 'modals', { pageTitle: 'Modal Windows', currentPage: 'modals', isModals: true });
});

app.get('/components/modal-dialogs', (req, res) => {
    renderWithLayout(res, 'modal-dialogs', { pageTitle: 'Modal Dialogs', currentPage: 'modal-dialogs', isModalDialogs: true });
});

app.get('/components/popconfirm', (req, res) => {
    renderWithLayout(res, 'popconfirm', { pageTitle: 'Popconfirm', currentPage: 'popconfirm', isPopconfirm: true });
});

app.get('/components/command-palette', (req, res) => {
    renderWithLayout(res, 'command-palette', { pageTitle: 'Command Palette', currentPage: 'command-palette', isCommandPalette: true });
});

app.get('/components/detail-panel', (req, res) => {
    renderWithLayout(res, 'detail-panel', { pageTitle: 'Detail Panel', currentPage: 'detail-panel', isDetailPanel: true });
});

app.get('/components/splitter', (req, res) => {
    renderWithLayout(res, 'splitter', { pageTitle: 'Splitter', currentPage: 'splitter', isSplitter: true });
});

app.get('/components/overflow', (req, res) => {
    renderWithLayout(res, 'overflow', { pageTitle: 'Overflow', currentPage: 'overflow', isOverflow: true });
});

app.get('/components/range-group', (req, res) => {
    renderWithLayout(res, 'range-group', { pageTitle: 'Range Group', currentPage: 'range-group', isRangeGroup: true });
});

app.get('/components/data-display', (req, res) => {
    renderWithLayout(res, 'data-display', { pageTitle: 'Data Display', currentPage: 'data-display', isDataDisplay: true });
});

app.get('/components/data-display-2', (req, res) => {
    renderWithLayout(res, 'data-display-2', { pageTitle: 'Data Display v2', currentPage: 'data-display-2', isDataDisplay2: true });
});

app.get('/components/data-visualization', (req, res) => {
    renderWithLayout(res, 'data-visualization', { pageTitle: 'Data Visualization', currentPage: 'data-visualization', isDataVisualization: true });
});

// KPI showcases — one page per indicator design (sidebar: KPI submenu)
app.get('/kpi/terminal-grid', (req, res) => {
    renderWithLayout(res, 'kpi-terminal-grid', { pageTitle: 'KPI · Terminal grid', currentPage: 'kpi-terminal-grid', isKpiTerminalGrid: true });
});

app.get('/kpi/sparkline-list', (req, res) => {
    renderWithLayout(res, 'kpi-sparkline-list', { pageTitle: 'KPI · Sparkline list', currentPage: 'kpi-sparkline-list', isKpiSparklineList: true });
});

app.get('/kpi/comparison-gauges', (req, res) => {
    renderWithLayout(res, 'kpi-comparison-gauges', { pageTitle: 'KPI · Comparison gauges', currentPage: 'kpi-comparison-gauges', isKpiComparisonGauges: true });
});

app.get('/kpi/hero-supporting', (req, res) => {
    renderWithLayout(res, 'kpi-hero-supporting', { pageTitle: 'KPI · Hero + supporting', currentPage: 'kpi-hero-supporting', isKpiHeroSupporting: true });
});

app.get('/kpi/bento', (req, res) => {
    renderWithLayout(res, 'kpi-bento', { pageTitle: 'KPI · Bento layout', currentPage: 'kpi-bento', isKpiBento: true });
});

app.get('/kpi/numeric-strip', (req, res) => {
    renderWithLayout(res, 'kpi-numeric-strip', { pageTitle: 'KPI · Numeric strip', currentPage: 'kpi-numeric-strip', isKpiNumericStrip: true });
});

app.get('/kpi/editorial-minimal', (req, res) => {
    renderWithLayout(res, 'kpi-editorial-minimal', { pageTitle: 'KPI · Editorial minimal', currentPage: 'kpi-editorial-minimal', isKpiEditorialMinimal: true });
});

app.get('/components/notifications', (req, res) => {
    renderWithLayout(res, 'notifications', { pageTitle: 'Notifications', currentPage: 'notifications', isNotifications: true });
});

// Tables
app.get('/tables/standard', (req, res) => {
    renderWithLayout(res, 'tables', { pageTitle: 'Tables', currentPage: 'tables', isTables: true });
});

app.get('/tables/sizing', (req, res) => {
    renderWithLayout(res, 'tables-sizing', { pageTitle: 'Tables - Sizing', currentPage: 'tables-sizing', isTablesSizing: true });
});

app.get('/tables/responsive', (req, res) => {
    renderWithLayout(res, 'tables-responsive', { pageTitle: 'Responsive Tables', currentPage: 'tables-responsive', isTablesResponsive: true });
});

app.get('/tables/filters', (req, res) => {
    renderWithLayout(res, 'table-filters', { pageTitle: 'Table Filters', currentPage: 'table-filters', isTableFilters: true });
});

app.get('/tables/smart-filters', (req, res) => {
    renderWithLayout(res, 'smart-filters', { pageTitle: 'Smart Filters', currentPage: 'smart-filters', isSmartFilters: true });
});

app.get('/tables/multi-select', (req, res) => {
    renderWithLayout(res, 'table-multi-select', { pageTitle: 'Multi-Select Across Filters', currentPage: 'table-multi-select', isTableMultiSelect: true });
});

app.get('/tables/comparison', (req, res) => {
    renderWithLayout(res, 'comparison', { pageTitle: 'Comparison Tables', currentPage: 'comparison', isComparison: true });
});

// Timeline
app.get('/timeline/simple', (req, res) => {
    renderWithLayout(res, 'timeline-simple', { pageTitle: 'Simple Timeline', currentPage: 'timeline-simple', isTimelineSimple: true });
});

app.get('/timeline/block', (req, res) => {
    renderWithLayout(res, 'timeline-block', { pageTitle: 'Timeline Block', currentPage: 'timeline-block', isTimelineBlock: true });
});

app.get('/timeline/feed', (req, res) => {
    renderWithLayout(res, 'timeline', { pageTitle: 'Timeline Feed', currentPage: 'timeline', isTimeline: true });
});

// Virtual Scroll
app.get('/virtual-scroll/demo', (req, res) => {
    renderWithLayout(res, 'virtual-scroll', { pageTitle: 'Virtual Scroll', currentPage: 'virtual-scroll', isVirtualScroll: true });
});

app.get('/virtual-scroll/code', (req, res) => {
    renderWithLayout(res, 'virtual-scroll-code', { pageTitle: 'Virtual Scroll Code', currentPage: 'virtual-scroll-code', isVirtualScrollCode: true });
});

// Showcases
app.get('/showcases/kpi-dashboard', (req, res) => {
    renderWithLayout(res, 'kpi-dashboard', { pageTitle: 'KPI Dashboard', currentPage: 'kpi-dashboard', isKpiDashboard: true });
});

app.get('/showcases/stat-fit-lab', (req, res) => {
    renderWithLayout(res, 'stat-fit-lab', { pageTitle: 'Stat Fit Lab', currentPage: 'stat-fit-lab', isStatFitLab: true });
});

app.get('/showcases/movies', (req, res) => {
    renderWithLayout(res, 'movies', { pageTitle: 'Movies', currentPage: 'movies', isMovies: true });
});

app.get('/showcases/movies/detail', (req, res) => {
    renderWithLayout(res, 'movie-detail', { pageTitle: 'Movie Detail', currentPage: 'movie-detail', isMovieDetail: true });
});

app.get('/showcases/movies-panel', (req, res) => {
    renderWithLayout(res, 'movies-panel', { pageTitle: 'Movies + Panel', currentPage: 'movies-panel', isMoviesPanel: true });
});

app.get('/showcases/form-demo', (req, res) => {
    renderWithLayout(res, 'form-demo', { pageTitle: 'Form Demo', currentPage: 'form-demo', isFormDemo: true });
});

// Tools
app.get('/tools/rtl-test', (req, res) => {
    renderWithLayout(res, 'rtl-test', { pageTitle: 'RTL Test', currentPage: 'rtl-test', isRtlTest: true });
});

app.get('/tools/font-test', (req, res) => {
    renderWithLayout(res, 'font-test', { pageTitle: 'Font Tuning Tool', currentPage: 'font-test' });
});

// Serve static files with cache headers (after routes so EJS takes precedence)

// Theme font/asset files (CSS references ../assets/fonts/ relative to dist/)
app.use('/dist/css/assets', (req, res, next) => {
    // Try each theme's assets directory
    for (const [themeName, themeDistPath] of Object.entries(themePackages)) {
        const themeRoot = path.join(themeDistPath, '..');
        const assetPath = path.join(themeRoot, 'assets', req.path);
        if (fs.existsSync(assetPath)) {
            return res.sendFile(assetPath);
        }
    }
    next();
});

// Theme CSS files from separate theme packages
app.get('/dist/css/themes/:theme.css', (req, res) => {
    const themeName = req.params.theme;
    const themeDistPath = themePackages[themeName];

    if (!themeDistPath) {
        return res.status(404).send(`Theme "${themeName}" not found`);
    }

    const themeCssPath = path.join(themeDistPath, `${themeName}.css`);

    if (!fs.existsSync(themeCssPath)) {
        return res.status(404).send(`Theme CSS file not found: ${themeCssPath}`);
    }

    res.setHeader('Content-Type', 'text/css');
    res.setHeader('Cache-Control', 'public, max-age=120');
    res.sendFile(themeCssPath);
});

// Theme manifest files (theme.json)
app.get('/api/themes/:theme/manifest', (req, res) => {
    const themeName = req.params.theme;
    const themeDistPath = themePackages[themeName];

    if (!themeDistPath) {
        return res.status(404).json({ error: `Theme "${themeName}" not found` });
    }

    // theme.json is in the package root, not dist
    const themeManifestPath = path.join(themeDistPath, '..', 'theme.json');

    if (!fs.existsSync(themeManifestPath)) {
        return res.status(404).json({ error: `Theme manifest not found for "${themeName}"` });
    }

    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', 'public, max-age=300'); // 5 minutes
    res.sendFile(themeManifestPath);
});

// All theme manifests combined
app.get('/api/themes/manifests', (req, res) => {
    const manifests = {};

    for (const [themeName, themeDistPath] of Object.entries(themePackages)) {
        const themeManifestPath = path.join(themeDistPath, '..', 'theme.json');

        if (fs.existsSync(themeManifestPath)) {
            try {
                const manifestContent = fs.readFileSync(themeManifestPath, 'utf-8');
                manifests[themeName] = JSON.parse(manifestContent);
            } catch (err) {
                console.error(`Error reading theme manifest for ${themeName}:`, err);
            }
        }
    }

    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', 'no-cache'); // themes can be added at runtime
    res.json(manifests);
});

// JSON schemas from core package (served at /schemas for public access)
app.use('/schemas', express.static(path.join(corePackagePath, 'schemas'), {
    maxAge: 120000 // 2 minutes
}));

// Fonts from core package
app.use('/fonts', express.static(path.join(corePackagePath, 'dist', 'fonts'), {
    maxAge: 120000 // 2 minutes
}));

// Also serve fonts from core package fonts/ directory (source fonts)
app.use('/fonts', express.static(path.join(corePackagePath, 'fonts'), {
    maxAge: 120000 // 2 minutes
}));

// CSS from core package
app.use('/dist/css', express.static(path.join(corePackagePath, 'dist', 'css'), {
    maxAge: 120000, // 2 minutes
    setHeaders: (res, filePath) => {
        res.setHeader('Cache-Control', 'public, max-age=120'); // 2 minutes
    }
}));

// Other dist files from core package
app.use('/dist', express.static(path.join(corePackagePath, 'dist'), {
    maxAge: 120000 // 2 minutes
}));

// SCSS source files from core package
app.use('/src/scss', express.static(path.join(corePackagePath, 'src', 'scss'), {
    maxAge: 120000 // 2 minutes
}));

// JavaScript files from demo (local) — no-cache + revalidate so edits show up on a
// normal reload instead of surviving 2 minutes and masquerading as "the fix didn't work".
app.use('/src/js', express.static(path.join(__dirname, 'js'), {
    maxAge: 0,
    etag: true
}));
// …then fall back to the core package's published src/js for any component whose
// JS lives only in core (single source of truth — no demo copy to keep in sync).
app.use('/src/js', express.static(path.join(corePackagePath, 'src', 'js'), {
    maxAge: 0,
    etag: true
}));

// Pure CSS foundation JS (the moved shell engines + the pureCss runtime).
// The 4 shell engines (fit, navbar-dropdown, sidebar-resize, container-breakpoint)
// + pure-css.js moved DOWN into @keenmate/pure-css; the demo loads them from here
// (classic IIFE scripts). Resolved through the workspace node_modules symlink.
app.use('/pure-css-js', express.static(path.join(__dirname, '..', 'node_modules', '@keenmate', 'pure-css', 'src', 'js'), {
    maxAge: 0,
    etag: true
}));

// Assets (images, icons) from demo (local)
app.use('/assets', express.static(path.join(__dirname, 'assets'), {
    maxAge: 120000 // 2 minutes
}));

// Snippets from core package
app.use('/snippets', express.static(path.join(corePackagePath, 'snippets'), {
    maxAge: 120000 // 2 minutes
}));

// Node modules (workspace root)
// Svelte apps (compiled treeview bundle, etc.)
app.use('/svelte-apps', express.static(path.join(__dirname, 'svelte-apps'), {
    maxAge: '0',
    etag: true
}));

app.use('/node_modules', express.static(path.join(__dirname, '..', 'node_modules'), {
    maxAge: 120000 // 2 minutes
}));

app.listen(port, () => {
    console.log(`Pure Admin server running at http://localhost:${port}`);
});